# Generated by Django 5.2.1 on 2025-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_servicio_centro_costo_alter_servicio_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='centro_costo',
            field=models.CharField(choices=[('Centro1', 'Centro de Costo 1'), ('Centro2', 'Centro de Costo 2'), ('Centro3', 'Centro de Costo 3'), ('Centro14', 'Centro de Costo 14'), ('Centro15', 'Centro de Costo 15'), ('Centro16', 'Centro de Costo 16'), ('Centro999', 'Centro de Costo 999')], default='Centro1', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='empresa',
            field=models.CharField(choices=[('Enel', 'Enel'), ('Vanti', 'Vanti'), ('Acueducto_Emservilla', 'Acueducto Emservilla'), ('Acueducto_Bogota', 'Acueducto Bogotá'), ('ETB', 'ETB'), ('Admon', 'Admon')], max_length=100),
        ),
    ]
