# Generated by Django 5.2.1 on 2025-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicio_centro_costo_alter_servicio_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo'), ('PSE', 'PSE'), ('Tarjeta', 'Tarjeta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
