# Generated by Django 5.2.1 on 2025-06-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_pago_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='quien_paga',
        ),
    ]
